github: Fix Nyrkiö action git hash
Github actions complains about the following so let's fix it:

  Error: Unable to resolve action `nyrkio/github-action-benchmark@ec6fe57`, the
  provided ref `ec6fe57` is the shortened version of a commit SHA, which is not
  supported. Please use the full commit SHA
  `ec6fe57d80fd83c83c10c6ef3f53899ce993aebb` instead.